### PR TITLE
v1.1.0

### PR DESCRIPTION
**Pull request by emmanuelmathot**
v1.1.0 release + update example to STAC 1.0.0

it is a a minor version because we add functionality in a backwards compatible manner

### CODE REVIEW

**Review by m-mohr — CHANGES_REQUESTED** [review]
The last PR was closed so quickly that I put my remarks here:

- The table row for nodata is broken
- Could there be cases where a no-data value is a string? Just checking whether we could run into conflicts...
- As there's the nearly finished PR #16, I'd wait with the release until that comes in, too.

**Comment by emmanuelmathot** [comment]
- nodata table row fixed
- nodata cannot be a string, always a number. All language have infinity and NaN as a number representation but not JSON
- merged

**Comment by vincentsarago** [comment]
@emmanuelmathot @m-mohr where are we on this?

**Comment by emmanuelmathot** [comment]
I requested the review by @m-mohr but I think he is off.
I addressed all his points of his review so I think we are good to go.

**Comment by m-mohr** [comment]
Yes, seems good. I'm just too busy right now.

**Pull request merged**
